### PR TITLE
Adds cloud-deployment dir with YAML spec for creating logs-based-metrics

### PR DESCRIPTION
**Pull request by nkinkade**
This PR creates a new subdirectory to contain Google Cloud Deployment Manager YAML spec files. It also creates a new spec file for logs-based metrics, creating, for now, a single logs-based metric for platform cluster kernel logs.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/gcp-config/38)

### CODE REVIEW

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: -- this is very cool!

> *[Reviewable](https://reviewable.io/reviews/m-lab/gcp-config/38#-:-MO2Rrtm9N0q1-MY26eC:b-hha6h9)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade and @stephen-soltesz)

___
*[cloud-deployment/logs-based-metrics.yaml, line 7 at r1](https://reviewable.io/reviews/m-lab/gcp-config/38#-MO2R_tqDisZhDSIxDuS:-MO2R_tqDisZhDSIxDuT:b-q01vwj) ([raw file](https://github.com/m-lab/gcp-config/blob/5d8aea1187ebff62229841e7a71fd10634d5ffca/cloud-deployment/logs-based-metrics.yaml#L7)):*
> ```YAML
>     description: Platform cluster kernel log message priorities
>     filter: |
>       resource.type="generic_node" resource.labels.location="mlab-sandbox" jsonPayload.SYSLOG_IDENTIFIER="kernel"
> ```

Is there a way to make the location label filter generic? The gcloud command requires specifying this value. I'm not suggesting a template, just is this filter necessary here?

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/gcp-config/38)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[cloud-deployment/logs-based-metrics.yaml, line 7 at r1](https://reviewable.io/reviews/m-lab/gcp-config/38#-MO2R_tqDisZhDSIxDuS:-MO2YLAbCJWYS_8hJRPg:bi6c1fc) ([raw file](https://github.com/m-lab/gcp-config/blob/5d8aea1187ebff62229841e7a71fd10634d5ffca/cloud-deployment/logs-based-metrics.yaml#L7)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is there a way to make the location label filter generic? The gcloud command requires specifying this value. I'm not suggesting a template, just is this filter necessary here?
</blockquote></details>

You are absolutely right, it is not necessary, since these logs are inherently project specific to begin with. Thanks for catching this hard-coded project reference. I've removed it.

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/gcp-config/38#-:-MO2YbxH-qwsmIsMOKaP:b-e77fnf)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by stephen-soltesz — APPROVED** [review]
lgtm :+1:

> *[Reviewable](https://reviewable.io/reviews/m-lab/gcp-config/38#-:-MO2li_n1xYYtPKuCZvi:b-aztd5r)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
