### PR TITLE
Implements the "trigger" operation in cbctl

### PR DESCRIPTION
**Pull request by nkinkade**
Currently, the `cbctl` command cannot trigger builds. This PR builds out that capability.

**TODO**: This PR does not implement any unit testing, which is already lacking in the current `cbctl` code.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/gcp-config/44)

### CODE REVIEW

**Comment by nkinkade** [comment]
NOTE: the changes to the file `job.go` were unintentional but necessary because apparently an update to the `storagetransfer/v1` library broke the existing implementation. I _think_ I fixed the issues, or at least it compiles. But I'm not sure how to test that it is working as expected.

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/gcp-config/44)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[transfer/job.go, line 23 at r1](https://reviewable.io/reviews/m-lab/gcp-config/44#-Ma3afseAtHclEkuwU9h:-Ma3afseAtHclEkuwU9i:b-7v0xkc) ([raw file](https://github.com/m-lab/gcp-config/blob/36a1530ffd2a64e29dea79513ef83d1a2c7a94e0/transfer/job.go#L23)):*
> ```Go
> 	"encoding/json"
> 
> 	"google.golang.org/api/storagetransfer/v1"
> ```

Did they really break this library?  That is very strange.
If I checkout master, change go mod to use either go 1.15 or 1.16, and go mod tidy, it still builds successfully.

**Review by gfr10598 — APPROVED** [review]
:lgtm: with one suggestion.

> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/gcp-config/44#-:-Ma9DGlv-KcobrwS9jFT:b-k18m3)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[cmd/cbctl/main.go, line 176 at r1](https://reviewable.io/reviews/m-lab/gcp-config/44#-Ma9CLGiBO6EnJRSlukX:-Ma9CLGj29FFax6UGtbO:bljgtzy) ([raw file](https://github.com/m-lab/gcp-config/blob/36a1530ffd2a64e29dea79513ef83d1a2c7a94e0/cmd/cbctl/main.go#L176)):*
> ```Go
> 	rtx.Must(err, "Failed to get default branch for repo: %s", repo)
> 
> 	return *r.DefaultBranch
> ```

How about returning r here, and then taking the DefaultBranch in the caller?
Same suggestion for the TagName above.
___
*[transfer/job.go, line 23 at r1](https://reviewable.io/reviews/m-lab/gcp-config/44#-Ma3afseAtHclEkuwU9h:-Ma63okP-ax3q6LfBdV2:b-xvoor5) ([raw file](https://github.com/m-lab/gcp-config/blob/36a1530ffd2a64e29dea79513ef83d1a2c7a94e0/transfer/job.go#L23)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

@gfr10598: I don't believe they broke the client. I think my branch (sandbox-kinkade) is requiring a much newer version of the Google APIs. go.mod in my branch includes this:

```
google.golang.org/api v0.46.0
```

... and the master branch includes:

```
google.golang.org/api v0.14.0
```

And sure enough, it looks like the API changed between those version. For example, in branch's version:

https://pkg.go.dev/google.golang.org/api@v0.46.0/storagetransfer/v1#TransferJobsService.List

And in the master branch version:

https://pkg.go.dev/google.golang.org/api@v0.14.0/storagetransfer/v1#TransferJobsService.List

I believe the changes to this file in this PR, should reflect the changes in the API between versions.
</blockquote></details>

Got it.  Sorry for the delay then.  I guess I was looking at another library that had a fixed major version number, so I didn't expect it to change.  But v0 has no rules I guess.

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/gcp-config/44)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gfr10598)

___
*[cmd/cbctl/main.go, line 176 at r1](https://reviewable.io/reviews/m-lab/gcp-config/44#-Ma9CLGiBO6EnJRSlukX:-Ma9zS62B2RfDUbBZmZ3:b-wcz1i8) ([raw file](https://github.com/m-lab/gcp-config/blob/36a1530ffd2a64e29dea79513ef83d1a2c7a94e0/cmd/cbctl/main.go#L176)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

How about returning r here, and then taking the DefaultBranch in the caller?
Same suggestion for the TagName above.
</blockquote></details>

I've done this now. It required renaming one of the functions to make sense. But now, instead of returning strings, they return structs, and the caller picks out the field value(s) it needs.

**Pull request merged**
